stages:
  train:
    cmd: python -m bhm.run_train
    deps:
      - src/bhm/run_train.py
      - src/bhm/train.py
      - src/bhm/model.py
      - src/bhm/data.py
    params:
      - experiment
      - train
      - seed
    outs:
      - models/model.eqx
    metrics:
      - dvclive/train/metrics.json:
          cache: false
    plots:
      - dvclive/train/plots/metrics:
          cache: false

  evaluate:
    cmd: python -m bhm.run_evaluate
    deps:
      - src/bhm/run_evaluate.py
      - src/bhm/curvature.py
      - src/bhm/evaluate.py
      - src/bhm/model.py
      - src/bhm/data.py
      - models/model.eqx
    params:
      - experiment
      - seed
      - chunk_size
    metrics:
      - dvclive/evaluate/metrics.json:
          cache: false
    plots:
      - dvclive/evaluate/plots/custom/approx_error.json:
          cache: false
